<?php
require_once 'helpers/TripHelper.php';
require_once 'config/db.php';

$db = new Database();
$aesKey = $db->aesKey;
$aesIv  = $db->aesIv;

// Dán nội dung body từ Trip vào đây (copy từ log)
$encryptedBody = 'mdoobfebjappcgfdjkdnlgjdcmgknfnjidfgcimdmlelabaoloddknnjhllffeicbckacjaleljobnafkjecnclicaigapnipfjgogboohiofaohmfjcpfdbphkpenkkicjlalcnaklpoodihchllomfahbeidclhmchnmbfeamajopmihneaohdaahnghinpgneggdloaghjladhdjfjjibddddjpofcmjghinacjgfkogooneidnjdpelggomkegckghajgdiclkfojghaemamlghongfjfoefbncckhleemakhdeimgbpnpoeflnabmnmjceoiijoaggfndncbpohdcafdhompcklmfbilaeckgkfminhclnpifipbincbngndlnfhadgojmckafdofkbbbkgfbammdgjhdfckenjhjhajhenajcpogghmfpfedcdfbmfahdhnodmkplhcfilemmhehjhkljpjnpmmkgclhbekkblmcddmlhaohodddlmefedjkejbbfkicnjgjmnnmpfpomacieddbnacgpphbplgliooeoamhffnfjnbdkhcijahpameefhldgegjckdcidofpinmoeflgmcogccehebaojdcegfjigfeccomoegekhfjfieifcjeghflldjdgjjegplihhccgfidahcnddmieglgfiflekmkmcddofdpgibfhpgcedpfniccifcgimfcimkobekkfakaladlkabkllmldmldiobmjilaaakgdchdbcebdkaeoimbcleegnodckiikpncadbeegnpbljjoeckeodffdadjicgkcoiglocoapmlnpfonlehcfnoooigiogihgbeccbilhhkaghjlhlilccbcigmibfkfnamdiooccaonlloindflaidnefhafggaidcghjenmggdobadocldndkkdhmapbdikobdbealnkalphpohmoedkopdijelbhkokbbbbjjfpbmnjajkfgjmiglihhclglnebebechdoddpbepjaoloialgllocnefmbmhjpajkegkdgpliiibolkpoggnfehkdhfjnhgjdfhnghblbgihcgejhkahjdkkmbgolbebkblopmdnagpghejholkaafokanljfihmjjlmmokpbjkhogbpfinnmbdekjnlhnmphfkdbjiblcbgjnfnohnephlclcibdbokjmjjihdmepnddfmdgjecggbfpcikbaplbalichdkgaghfalflommiibbcagkolcnmoikiggpeplgojgpfbgdleeajcfpjcacmgopenccebnmbbhbbiiahijabigacdfeeabnklpbdabcflnjkpeeaeenkhneoggpcdopjnkjhaldelihgapglgbgcbmgfnlnhojabhageifjdckcdokfdaiojndlglekoiimcnllbajceeokcknllgoeokieenaeffcgdhghjbgnhmnpnmldbhnfeldccpfpaajcakajihnnkdaciainadofmchlljpbbiieknhhdenoilcgoikkngmnhamamfdhpjeiikjiigofadnnffkgibmjleddcankjeejkcoledconlcmlnjankicejkagaaifiacpnbahpnefalndkeakejhgdfkkfnjhccpgigahdfkmnlkpkcenapooaopjhhnhfpcdcjlbceehadakmaejodehlheinkpoomilcbidohalokcddlonldbdjmjdiljdcfobgccfinlidjcbhgcoeopfgkfdooboidfogilenoekgboidoodpegemhbfkhgjcofijncfbdokbebfipencliiepnlkjoofcecpdjpphjndnnhbbeeoadnpmlcmodghdpemhnolgapambkchbjeaoldkckonkiljnopdhgihkfcifghgmnnlmjcngmjbcnmddopokmjdlcdnacmcnocjknpdblgkjbonfbannhjbpkflmcieakambmnagggcadbbjnbdfbepgapiehaponcclhhojbpeegmkcimpafcngalickoojhahgincflpogmkngpgdcigmjnfciccfggibmfmamkoldfegkbefgmhkllombfgjeipmfjllgddommonbnjbjclgfocnaigjegjdnmmfofgphdbapdhgllehnbbaamnapnaibbfoejdkdkdkiagjmicghipgjmoelhopmbhigocfeiokekgbjejgafcbcfcahlniohblhdamdiodhlhjdiolcjlomefmcgmeiekancbcfbbojiinfpnlnnggekpfiakdbgdllehofihjgkcbkkdabbogcpochfmcabmpmdlkoboihpnefjancjhellafadjbncilbipkkceekcngjenajdpbegmkfofobgemlalgflmnijfalnmdgnhaacgfhmcmejamdelmnjipeaimhaipndofiegfalfagibnflookcppbeajmffdnmpphdidaobjbafmnmhjmmnebkieebfghhaclpihlnckgmaajmhfiblobhaghajockmplhbkfnpmgcdifpbobnnkjnacemkmgkmcgfaopjnplopgcniggnckkmfehjepofoehkobjbfeekcpjflagpblneciehofhciemaiockmdghbkjdbicemoaiilnbkakldpeahklgbdlgllagefbkammmmckokmekladbhpnjhifpoimkjgclgikoedeckaalfbfmijpelckgldclafojeejeebfjfljaggohhneipaifpkbachdfpgmanfeeaijponcpenjgocgjijcpogadbcebjbiapbomfbndokpbnllfbokgengbdjdjkoeiacldlegpkdpl';

$decrypted = TripHelper::decryptBody($encryptedBody, $aesKey, $aesIv);

if ($decrypted) {
    echo "✅ Giải mã thành công:\n";
    echo $decrypted;
} else {
    echo "❌ Giải mã thất bại.\n";
}
